/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Interaction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SpawnRegistered": {
      "arn": string
      "type": "aws.sfn/stateMachine.StateMachine"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}