name: Deploy

on:
  push:
    tags: ['**']

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install

      - run: pnpm exec sst telemetry disable

      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_APP_PUBLIC_KEY: ${{ secrets.DISCORD_APP_PUBLIC_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_SPAWN_ALERT_CHANNEL_ID: ${{ secrets.DISCORD_SPAWN_ALERT_CHANNEL_ID }}
          DISCORD_WINDOW_UPDATES_CHANNEL_ID: ${{ secrets.DISCORD_WINDOW_UPDATES_CHANNEL_ID }}
          SST_STAGE: prod
        run: |
          pnpm exec sst deploy
          pnpm exec sst shell -- tsx discord/register-commands.ts
